name: Build and Push Synapse Docker Image

on:
  push:
    branches:
      - master
      - develop    
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Detect Synapse site-packages path
        run: |
          SITE_PACKAGES=$(docker run --rm matrixdotorg/synapse:latest \
            python3 -c "import site; print(site.getsitepackages()[0])")
          echo "SITE_PACKAGES=${SITE_PACKAGES}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            SYNAPSE_SITE_PACKAGES=${{ env.SITE_PACKAGES }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

