name: Build and Push Synapse Docker Image

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  pages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Detect Synapse site-packages path
        run: |
          SITE_PACKAGES=$(docker run --rm --entrypoint python3 matrixdotorg/synapse:latest \
            -c "import site; print(site.getsitepackages()[0])")
          echo "SITE_PACKAGES=${SITE_PACKAGES}" >> $GITHUB_ENV

      - name: Lowercase repo name
        run: echo "REPO_LOWER=$(echo '${GITHUB_REPOSITORY}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            SYNAPSE_SITE_PACKAGES=${{ env.SITE_PACKAGES }}
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}:latest
            ghcr.io/${{ env.REPO_LOWER }}:${{ github.sha }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
